# Generated by Django 4.1.6 on 2023-02-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0005_remove_trait_pets"),
        ("pets", "0002_alter_pet_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
