# Generated by Django 4.1.6 on 2023-02-13 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_pet_traits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="traits",
        ),
    ]
