# Generated by Django 4.1.6 on 2023-02-13 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_pet_trait"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="trait",
            new_name="traits",
        ),
    ]
