# Generated by Django 4.1.6 on 2023-02-13 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_rename_trait_name_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
