# Generated by Django 4.1.6 on 2023-02-13 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0006_trait_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
